### ISSUE TITLE
AlpineJs i VueJs xoquen

### ISSUE THREAD

**Issue by acacha** [acacha/casteaching#13]
Nomes utilitzem Vue a https://casteaching.alumnedam.me/vue/manage/videos

Però el carreguem a arreu per que ho posem al app.js principal. 

VueJs i alpineJS xoquen per exemple al utilitzar el component x-status ja que dona un warning al veure un hiddem que es de alpinejs però vue el considera del component root

**Comment by acacha** [comment]
Solució : restringir l'scope de vuejs posant el id="app" només a la plantilla de vue manage videos

**Comment by acacha** [comment]
Vegeu el commit...

**Comment by daudi44** [comment]
![Captura de pantalla de 2022-01-31 19-07-18](https://user-images.githubusercontent.com/75979331/151848752-ebfb9d2d-4058-4407-99f2-93f4beb52c8f.png)

**Comment by acacha** [comment]
US explico per que a passat aquest error:
- Primer vam fer la aplicació amb PHP i AlpineJS (apartat videos)
- Després hem fet Videos Vue amb VueJS
- Però tots dos utilitzen ara mateix el mateix layout i xoquen
- És un típic exemple de com encara que no ho sembli dos apartats que no haurien de tenir implicació entre si el tenen. Vaja que hem afegit funcionalitat (apartat VueJS) i ens hem carregat funcionalitat ja existent.
- El error apareix quan utilitzem el component status (el fem visible) per mostrar que un vídeo s'ha pujat correctament
- És un problema de AlpineJS i VueJS a la mateixa pàgina només es pot utilitzar en part diferents del document
Passos a tenir en compte si us surt el error comentat anteriorment (comentari anterior) per Dani:
- Tenim el vue activat per a tot el div que conté tota la app (div amb id #app), no cal tant i així evitarem conflicte amb AlpineJS

Fitxers a canviar:
- [resources/js/app.js](https://github.com/acacha/casteaching/commit/683687c1e0c89522ff086e370e0d5c74fd980633#diff-583a1f586bc298813341bce6fec77a1f6338f2559471fe600f15a18316fe82bd)
- [resources/views/layouts/casteaching.blade.php](https://github.com/acacha/casteaching/commit/683687c1e0c89522ff086e370e0d5c74fd980633#diff-cb08c0576767187d859e52c297645c03d1526becfc8ca7a73fd672806ad88492)
- [resources/views/videos/manage/vue/index.blade.php ](https://github.com/acacha/casteaching/commit/683687c1e0c89522ff086e370e0d5c74fd980633#diff-948e1f55e76354066613bbe853f47a70f252159c31bc445d3751932f65fc50d4)
